kind = "mobile"
previewPath = "/"
title = "Tarkeez"
version = "1.0.0"
id = "artifacts/tarkeez"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 20383

[services.development]
run = "pnpm --filter @workspace/tarkeez run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/tarkeez", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/tarkeez", "run", "serve" ]

[services.env]
PORT = "20383"
BASE_PATH = "/"
