import whitelistData from "./whitelist.json";

// Generated by scripts/normalize-whitelist.mjs from whitelist-source.txt.
// Matching is suffix-based — listing "khanacademy.org" also covers
// "courses.khanacademy.org" and any other subdomain.
export const WHITELIST: ReadonlySet<string> = new Set(whitelistData as string[]);

// Hand-curated explicit overrides — blocked regardless of Tier 2/3 output.
// Keep small; the safety net handles the long tail. Add an entry only when
// a domain is clearly off-topic and the LLM might be fooled.
export const BLACKLIST: ReadonlySet<string> = new Set([
  "facebook.com",
  "instagram.com",
  "tiktok.com",
  "twitter.com",
  "x.com",
  "reddit.com",
  "netflix.com",
]);
